"""Ajout modele utilisateur

Revision ID: 2bd9cb4fcf8c
Revises: e2e7d31fb4c0
Create Date: 2026-05-19 17:59:16.886468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd9cb4fcf8c'
down_revision: Union[str, Sequence[str], None] = 'e2e7d31fb4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonyme', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateur_id'), 'utilisateur', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateur_pseudonyme'), 'utilisateur', ['pseudonyme'], unique=True)
    op.add_column('taches', sa.Column('id_utilisateur', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'taches', 'utilisateur', ['id_utilisateur'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taches', type_='foreignkey')
    op.drop_column('taches', 'id_utilisateur')
    op.drop_index(op.f('ix_utilisateur_pseudonyme'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
