"""ajout de la colonne etat

Revision ID: e2e7d31fb4c0
Revises: 090240457aeb
Create Date: 2026-05-03 16:14:55.407765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e7d31fb4c0'
down_revision: Union[str, Sequence[str], None] = '090240457aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taches', sa.Column('etat', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taches', 'etat')
    # ### end Alembic commands ###
